services:
  clip-script:
    build: .
    container_name: clip-script
    ports:
      - "3013:3013"
    environment:
      - MONGO_URI=mongodb://172.17.0.1:27017/clip-script-platform
    restart: unless-stopped
