services:
  clip-script:
    build: .
    container_name: clip-script
    network_mode: host
    environment:
      - MONGO_URI=mongodb://127.0.0.1:27017/clip-script-platform
    restart: unless-stopped
